[package]
name = "scall-monitor"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "smonitor"
path = "src/main.rs"

[dependencies]
eframe = "0.36"
egui_extras = "0.36"
sysinfo = "0.39"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Performance",
    "Win32_System_SystemInformation",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }
